version: '2.1'

networks:
  backend:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=elepath_localdocker
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root"]
        timeout: 5s
        retries: 12
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    volumes:
      - ./:/myapp
    ports:
      - '4000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RACK_ENV=localdocker
    networks:
      - backend

