version: '2'

networks:
  backend:
    driver: bridge

volumes:
  db_data:

services:
  db:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8_unicode_ci']
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=elepath_localdocker
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    volumes:
      - ./:/myapp
    ports:
      - '4000:3000'
    depends_on:
      - db
    environment:
      - RACK_ENV=localdocker
    networks:
      - backend

